import fs from 'fs';

const content = `import type { MarketItem } from '../types';

export const INITIAL_EVENTS: MarketItem[] = [
  {
    id: 'fed-september-2026',
    slug: 'fed-decision-in-september',
    title: 'Fed Decision in September: 50+ bps cut?',
    titleJa: '米FRBが9月会合で0.5%以上の大幅利下げを実施するか？',
    question: 'Will the Fed decrease interest rates by 50+ bps after the September meeting?',
    questionJa: '米連邦準備制度理事会（FRB）は9月のFOMCで0.5%以上の利下げを実施するか？',
    category: 'economy',
    categoryLabel: '📊 経済・金利・暗号資産',
    iconUrl: 'https://polymarket-upload.s3.us-east-2.amazonaws.com/fed-decision-in-september-762-c4RyWuxRPo1L.jpg',
    worldProbYes: 18,
    worldProbNo: 82,
    probChange24h: 0,
    volume24hUsd: 566055,
    totalVolumeUsd: 34467334,
    endDate: '2026-09-30',
    japanVotes: {
      yes: 0,
      no: 0,
      total: 0,
      percentYes: 50,
    },
    comments: []
  },
  {
    id: 'us-president-2028',
    slug: 'presidential-election-winner-2028',
    title: 'US Presidential Election Winner 2028',
    titleJa: '2028年 次期米大統領選挙の勝者は？（JDヴァンス優勢か）',
    question: 'Will JD Vance win the 2028 US Presidential Election?',
    questionJa: 'JDヴァンスが2028年米大統領選で勝利するか？',
    category: 'politics',
    categoryLabel: '🌐 国際・社会',
    iconUrl: 'https://polymarket-upload.s3.us-east-2.amazonaws.com/presidential-election-winner-2024-afdda358-219d-448a-abb5-ba4d14118d71.png',
    worldProbYes: 26,
    worldProbNo: 74,
    probChange24h: 0,
    volume24hUsd: 567270,
    totalVolumeUsd: 686600229,
    endDate: '2028-11-08',
    japanVotes: {
      yes: 0,
      no: 0,
      total: 0,
      percentYes: 50,
    },
    comments: []
  },
  {
    id: 'openai-gpt5-release',
    slug: 'openai-gpt5-or-next-flagship-release',
    title: 'OpenAI to release Next-Gen Frontier Model by Q4?',
    titleJa: 'OpenAIは年内に次世代フロンティアモデル（GPT-5級）を正式公開するか？',
    question: 'Will OpenAI release its next flagship frontier model before Q4 2026?',
    questionJa: 'OpenAIは2026年第4四半期までに新世代フラッグシップモデルを一般公開するか？',
    category: 'tech',
    categoryLabel: '⚡ AI・テック',
    iconUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=120&q=80',
    worldProbYes: 78,
    worldProbNo: 22,
    probChange24h: 0,
    volume24hUsd: 1240890,
    totalVolumeUsd: 18920400,
    endDate: '2026-12-31',
    japanVotes: {
      yes: 0,
      no: 0,
      total: 0,
      percentYes: 50,
    },
    comments: []
  },
  {
    id: 'boj-rate-hike-2026',
    slug: 'bank-of-japan-rate-hike-by-december',
    title: 'Bank of Japan to raise policy rate above 0.75% in 2026?',
    titleJa: '日銀は2026年内に追加利上げ（政策金利0.75%以上）を実施するか？',
    question: 'Will the Bank of Japan raise its policy interest rate above 0.75% by December 2026?',
    questionJa: '日本銀行は2026年12月までに政策金利を0.75%以上に引き上げるか？',
    category: 'economy',
    categoryLabel: '📊 経済・金利・暗号資産',
    iconUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=120&q=80',
    worldProbYes: 68,
    worldProbNo: 32,
    probChange24h: 0,
    volume24hUsd: 890450,
    totalVolumeUsd: 14200000,
    endDate: '2026-12-31',
    japanVotes: {
      yes: 0,
      no: 0,
      total: 0,
      percentYes: 50,
    },
    comments: []
  },
  {
    id: 'bitcoin-hit-120k',
    slug: 'what-price-will-bitcoin-hit-in-2026',
    title: 'Bitcoin to reach $120,000 in 2026?',
    titleJa: 'ビットコイン（BTC）は2026年内に12万ドル（約1800万円）を突破するか？',
    question: 'Will Bitcoin reach $120,000 by December 31, 2026?',
    questionJa: 'ビットコインの価格は2026年12月末までに120,000ドルに到達するか？',
    category: 'economy',
    categoryLabel: '📊 経済・金利・暗号資産',
    iconUrl: 'https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png',
    worldProbYes: 54,
    worldProbNo: 46,
    probChange24h: 0,
    volume24hUsd: 1420900,
    totalVolumeUsd: 53025036,
    endDate: '2026-12-31',
    japanVotes: {
      yes: 0,
      no: 0,
      total: 0,
      percentYes: 50,
    },
    comments: []
  },
  {
    id: 'ucl-2027-champion',
    slug: 'uefa-champions-league-2027-champion',
    title: 'UEFA Champions League 2027: Real Madrid or PSG?',
    titleJa: 'UEFAチャンピオンズリーグ2027：優勝クラブ予測',
    question: 'Will Real Madrid win the 2026-27 UEFA Champions League?',
    questionJa: 'レアル・マドリードが2026-27 UEFA Champions Leagueで優勝するか？',
    category: 'sports',
    categoryLabel: '⚾ スポーツ',
    iconUrl: 'https://polymarket-upload.s3.us-east-2.amazonaws.com/uefa-champions-league-2025-26-which-teams-qualify-StbSIjaEx2St.png',
    worldProbYes: 28,
    worldProbNo: 72,
    probChange24h: 0,
    volume24hUsd: 915384,
    totalVolumeUsd: 9329554,
    endDate: '2027-06-01',
    japanVotes: {
      yes: 0,
      no: 0,
      total: 0,
      percentYes: 50,
    },
    comments: []
  }
];
`;

fs.writeFileSync('/Users/aikirishimaphoenix/AI-Company/projects/mirai-forecast/src/data/initialEvents.ts', content);
console.log('✅ initialEvents.ts cleaned successfully');
